version: v1.0

plan: standard-2

paths:
  - src/**
  - tests/**
  - configs/**
  - typeTemplates/**
  - .scripts/**
  - .neetoci/default.yml
  - package.json
  - yarn.lock
  - .node-version
  - .nvmrc
  - .prettierrc.js
  - .eslintrc.js
  - .eslintignore
  - jest.config.js
  - jsconfig.json
  - resolve.js
  - "*.config.*"

global_job_config:
  setup:
    - checkout
    - neetoci-version node 22.13
    - cache restore
    - yarn install --frozen-lockfile
    - cache store
  jobs:
    - name: CiChecks
      commands:
        - .scripts/run_eslint_on_modified_files.sh
        - yarn test

triggers:
  - event: branch
    branch_name: main
  - event: pull_request
